import { Download, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AnalysisResult } from '@/types/analysis';
import { useToast } from '@/hooks/use-toast';

interface PDFDownloadProps {
  analysis: AnalysisResult;
}

const PDFDownload = ({ analysis }: PDFDownloadProps) => {
  const { toast } = useToast();

  const generatePDFContent = (type: 'clinical' | 'patient') => {
    const title = type === 'clinical' 
      ? 'Clinical Document Summary' 
      : 'Patient-Friendly Summary';
    
    const summary = type === 'clinical' 
      ? analysis.summaries.clinical 
      : analysis.summaries.patient;

    let content = `
${title}
${'='.repeat(50)}
Generated: ${new Date(analysis.analyzedAt).toLocaleString()}
Department: ${analysis.department}
Severity: ${analysis.severity.level.toUpperCase()}

SUMMARY
${'-'.repeat(30)}
${summary}

`;

    if (analysis.keyFindings.length > 0) {
      content += `
KEY FINDINGS
${'-'.repeat(30)}
${analysis.keyFindings.map(f => `• ${f}`).join('\n')}

`;
    }

    if (analysis.medications.length > 0) {
      content += `
MEDICATIONS
${'-'.repeat(30)}
${analysis.medications.map(m => `• ${m}`).join('\n')}

`;
    }

    if (analysis.followUpInstructions.length > 0) {
      content += `
FOLLOW-UP INSTRUCTIONS
${'-'.repeat(30)}
${analysis.followUpInstructions.map(i => `• ${i}`).join('\n')}

`;
    }

    if (analysis.diagnoses.length > 0) {
      content += `
DIAGNOSES
${'-'.repeat(30)}
${analysis.diagnoses.map(d => `• ${d}`).join('\n')}

`;
    }

    if (analysis.abbreviations.length > 0 && type === 'patient') {
      content += `
MEDICAL TERMS EXPLAINED
${'-'.repeat(30)}
${analysis.abbreviations.map(a => `${a.abbr} = ${a.full}`).join('\n')}

`;
    }

    content += `
${'='.repeat(50)}
DISCLAIMER: This summary is generated by an AI system for 
educational purposes only. It is NOT a substitute for 
professional medical advice, diagnosis, or treatment.
`;

    return content;
  };

  const downloadAsText = (type: 'clinical' | 'patient') => {
    const content = generatePDFContent(type);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${type}-summary-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: 'Download Started',
      description: `Your ${type} summary is being downloaded.`
    });
  };

  return (
    <div className="medical-card">
      <div className="flex items-center gap-2 mb-4">
        <FileText className="h-5 w-5 text-primary" />
        <h3 className="text-lg font-semibold text-foreground">Download Summary</h3>
      </div>
      
      <p className="text-sm text-muted-foreground mb-4">
        Download the document analysis as a text file for your records.
      </p>

      <div className="flex flex-wrap gap-3">
        <Button 
          variant="outline" 
          onClick={() => downloadAsText('clinical')}
          className="gap-2"
        >
          <Download className="h-4 w-4" />
          Clinical Summary
        </Button>
        <Button 
          variant="outline" 
          onClick={() => downloadAsText('patient')}
          className="gap-2"
        >
          <Download className="h-4 w-4" />
          Patient Summary
        </Button>
      </div>
    </div>
  );
};

export default PDFDownload;
